[workspace]
members = ["crates/lectara-service", "crates/lectara-cli"]
resolver = "2"

[workspace.package]
authors = ["seridescent"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
